language: node_js

node_js:
  - '5.6'

env:
  - CXX=g++-4.8

addons:
  apt:

    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8

before_install:
  - npm install -g npm@latest

after_install:
  - npm config set tag-version-prefix "" --global
  - npm config set tag-version-prefix ""

before_script:
  - npm version `git describe --tags` --no-git-tag
  - cat package.json | grep version

script:
  - gulp build
  - gulp test
  - gulp docs

before_deploy:
  - rm -rf src/test

deploy:
  provider: npm
  email: peterc@aetheric.co.nz
  skip_cleanup: true
  api_key:
    secure: ?
  on:
    repo: aetheric/vodoun
    all_branches: true
